fixed

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -30,3 +30,34 @@ jobs:
     - name: Build with Maven
       run: mvn install -Djava.awt.headless=true -DskipTests
 
+  validate:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Validate Commit Messages
+        run: |
+          PROHIBITED_WORDS = "Bitches | Bomba | Bombaclaat | Fuck | Shit" 
+          REQUIRED_WORDS = " fixed | Changed | cleaned up"
+          
+           # Get commit messages
+          COMMITS=$(git log --format=%s ${{ github.event.before }}..${{ github.sha }})
+
+          # Check for prohibited words
+          for WORD in $PROHIBITED_WORDS; do
+            if echo "$COMMITS" | grep -E "$WORD" > /dev/null; then
+              echo "Commit message contains prohibited word: $WORD"
+              exit 1
+            fi
+          done
+
+          # Check for required words
+          if ! echo "$COMMITS" | grep -E "$REQUIRED_WORDS" > /dev/null; then
+            echo "Commit message must contain one of the following words: $REQUIRED_WORDS"
+            exit 1
+          fi
+
+          echo "Commit messages are valid."
+        
+          |
